In [4]:
import numpy as np

In [6]:
matrix = np.array([1,2,3,4,5,6])
vector = np.array([1,2,3,4,5,6])

In [8]:
result = matrix + matrix
result

array([ 2,  4,  6,  8, 10, 12])

In [10]:
transpose = matrix.T
transpose 

array([1, 2, 3, 4, 5, 6])

In [12]:
#DOT PRODUCT

In [14]:
vector1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

dot_product = np.dot(vector1, vector2)
dot_product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [16]:
#Determinant

In [22]:
determinant = np.linalg.det(vector1)
print(determinant)

-9.51619735392994e-16


In [24]:
inverse = np.linalg.inv(vector2)
print(inverse)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [26]:
norm = np.linalg.norm(vector)
norm

9.539392014169456

In [28]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = np.linalg.solve(A, B)
X

array([[-0.225, -0.2  ,  0.   ],
       [ 2.45 ,  1.4  ,  0.   ],
       [-1.225, -0.2  ,  1.   ]])

# CALCULAS

In [32]:
from scipy.integrate import dblquad

In [34]:
def f(x,y):
    return x**2 + x**2

In [40]:
3**2

9

In [42]:
x_lower = 0
x_upper = 1
y_lower = 0
y_upper = 1

In [46]:
integral, error = dblquad(f, x_lower, x_upper, lambda y: y_lower, lambda y: y_upper)

In [50]:
print("Intergral:", integral)
print("Error:", error)

Intergral: 0.6666666666666667
Error: 7.401486830834377e-15


In [52]:
from scipy.integrate import quad

def f(x):
    return x**2

area, error = quad(f, 0, 2)

print("Area under the curve:",area)
error

Area under the curve: 2.666666666666667


2.960594732333751e-14

In [54]:
#Rank

In [56]:
matrix = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
rank = np.linalg.matrix_rank(matrix)
print("Rank of the matrix:",rank)

Rank of the matrix: [2 2]
